---
title: "JS 비동기 예외 처리"
execrpt: "js 비동기 예외 처리 방식"
toc: true
toc_sticky: true
categories:
  - JS
tags:
  - JS
  - err
last_modified_at: 2022-10-04
---
## 비동기 처리에 대한 예외처리
### 예제 1
```js
const data=[1,2,3];
// try-catch는 동기 방식으로 동작하므로 비동기 방식으로 동작하는 timer처리와 ajax에는 대응하지 못한다.
try{

    setTimeout(()=>{
        // 이 부분만 별도의 구역에서 실행되므로 에러가 발생하더라도 try의 영향을 받지 않는다.
        console.log(`배열탐색시작`);
        for(let i =0; i<10; i++){
            console.log(data[i].toFixed(2));
        }
        // 에러가 발생하여 프로그램이 중단되므로 이 메시지는 표시되지 않는다.
        console.log(`배열탐색종료`);
    },1000);
}catch(err){
    // setTimeout()과 같은 비동기 함수는 처리하지 못하기 때문에 이 블록은 실행되지 않는다.
    console.log(`에러발생(2)`);
    console.log(err);
}
console.log(`프로그램 종료`); // 표시안됨
```
### 예제 2
```js
const data = [1,2,3];

// timer처리와 같은 비동기 방식의 예외처리는 콜백함수 내부에서 처리해야 한다.
setTimeout(()=>{

    try{
        console.log(`배열탐색시작`);
        for(let i =0; i<10; i++){
            console.log(data[i].toFixed(2));
        }
    } catch (err){
        console.log(`에러발생(2)`);
        console.log(err.name);
        console.log(err.message);
    }
    // 콜백함수 내부에서 처리된 예외처리는 발생한 에러 상황을 처리할 수 있기 때문에
    // 아래 코드는 정상적으로 실행된다.
    console.log(`배열탐색종료`);
}, 1000);
console.log(`프로그램 종료`);
```
**순서**  

프로그램 종료 -> 배열탐색시작 -> 1.00 -> 2.00 -> 3.00 -> 에러발생(2) -> TypeError -> Cannot read properties of undefined (reading 'toFixed') -> 배열탐색종료

## callback-hell
1초 후 `당신의 추첨 결과는..?` 이라는 message 표시. 1~9에 대한 랜덤값이 짝수이면 당첨, 홀수이면 꽝. 그 결과를 3초 후에 표시. 타이머에 대한 작업 종료 후 이어서 새로운 타이머를 만들어 진행.
```js
random = (n1,n2) =>{
    return parseInt(Math.random()*(n2-n1+1)+n1);
}
setTimeout(()=>{
    console.log(`당신의 추첨 결과는..?`);

    const lucky = random(1,9);
    setTimeout(()=>{
        console.log(lucky % 2 == 0 ? `당첨!` : `꽝!`);
    },3000);
},1000);
console.log(`~~~~추첨중~~~~`);
```
**순서**  
추첨중 -> 당신의 추첨 결과는..? -> 당첨! or 꽝!
## Promise
비동기 처리로 실행되는 함수에 대한 결과 처리를 별도의 로직으로 실행할 수 있는 기법.  
Promise 생성자 함수를 통해 인스턴스화한다. Promise 생성자 함수는 비동기 작업을 수행할 콜백 함수를 인자로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인자로 전달받는다.  
* 생성자 : constructor는 객체를 만드는 역할을 하는 함수다.
* 인스턴스화 : 비슷한 성질을 가진 여러개의 객체를 만들기 위해서 생성자 함수, Constructor를 만들어 찍어내듯이 사용하는데 이렇게 생성된 객체를 인스턴스라 부른다.(class, prototype)


```js
random = (n1,n2) =>{
    return parseInt(Math.random()*(n2-n1+1)+n1);
}
// promise를 가동하기 위해서는 Promise객체를 리턴하는 함수가 필요함.
getLuckyResult = () => {
    // promise객체는 resolve 함수와, reject 함수를 파라미터로 받는 콜백이 필요함.
    return new Promise((resolve, reject)=>{
        // 이 안에서 비동기 작업을 시작함.
        setTimeout(()=>{
            console.log(`당신의 추첨 결과는..?`);
            const lucky = random(1,9);
            if(lucky % 2 == 0){
                // 작업의 결과가 성공으로 판별된 경우 resolve()를 호출한다.
                // 파라미터는 단 하나만 가능.
                // 여러 개의 정보를 보내야 하는 경우 JSON 구조가 적절.
                resolve({msg : `당첨!`, a:1, b:2, c:3});
            }else{
                reject({msg:`꽝!`, d:-1, e:-2});
            }
        },1000);
    });
}
/** Promise객체를 리턴받기 위한 함수를 호출.
 * getLuckyResult()함수 내부에서 Promise객체가 생성되면서,
 * Promise 클래스에 전달한 생성자 파라미터(콜백함수)가 실행될 것이다.
 * --> resolve 혹은 reject 가 호출된 상태라는 의미.
 */
const mypromise = getLuckyResult();
/** Promise객체가 생성되는 과정에서 생성자로 전달된 콜백함수의 실행 결과를 감지하는 부분.
 * resolve 혹은 reject 중에서 실행된 함수가 무엇인지 감지.
 * 비동기 작업의 결과를 알아냄
 * 타이머 종료에 이은 후속처리가 가능하다는 의미
 */
mypromise.then( ( {msg,a,b,c} ) => {
    // [작업성공] : resolve() 실행됨
    console.log(msg,a,b,c);
} ).catch( ( {msg,d,e} ) => {
    // [작업실패] : reject() 실행됨
    console.error(msg,d,e);
}).finally(()=>{
    // 성공 실패 여부에 상관 없이 무조건 실행 (생략 가능)
    console.log(`끝!`);
});
```
순서 : 당신의 추첨 결과는..? -> 당첨! 1 2 3 -> 끝!  
## async-await

`예시`
```js
random = (n1,n2) =>{
    return parseInt(Math.random()*(n2-n1+1)+n1);
}
getLuckyResult = () => {
    return new Promise((resolve, reject)=>{
        setTimeout(()=>{
            console.log(`당신의 추첨 결과는..?`);
            const lucky = random(1,9);
            if(lucky % 2 == 0){
                resolve({msg : `당첨!`, a:1, b:2, c:3});
            }else{
                reject({msg:`꽝!`, d:-1, e:-2});
            }
        },1000);
    });
}
/** Promise를 리턴하는 함수를 호출하기 위해 새로운 async 함수를 정의
 * 주로 즉시 실행 함수 형태로 정의됨.
 * -> 익명함수 전체를 괄호()로 묶어버리고 그 뒤에 호출을 위한 ()를 연달아 넣는 형식
 * (async function() {
 */
(async () =>{
    let result = null;

    // Promise를 리턴받는 과정을  await 키워드를 적용하여 처리, 예외처리도 적용.
    try{
        // getLuckyResult에서 resolve()가 호출되며 전달한 파라미터는 그냥 리턴
        result = await getLuckyResult();
        console.log(result.msg, result.a, result.b, result.c);
    }catch(e){
        // getLuckyResult에서 reject()가 호출되며 전달한 파라미터는 예외객체(e)로 전달
        console.error(e.msg, e.d, e.e);
    }finally{
        // 생략가능
        console.log(`끝!!!`);
    }
})();
```